<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable><OutputType>Exe</OutputType><TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="ModelContextProtocol" />
    <ProjectReference Include="../../src/CustomerDashboard.Api/CustomerDashboard.Api.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>

